# SPDX-FileCopyrightText: 2024 Christina SÃ¸rensen
# SPDX-License-Identifier: EUPL-1.2
[toolchain]
# NOTE: don't forget to update the unit-tests workflow when changing this
channel = "1.83"
components = [
  "rustfmt",
  "rustc",
  "rust-src",
  "rust-analyzer",
  "cargo",
  "clippy",
]
profile = "minimal"
