name: Apt Installation
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
    paths:
      - 'deb.asc'
      - '.github/workflows/apt.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'deb.asc'
      - '.github/workflows/apt.yml'
jobs:
  apt_installation:
    runs-on: ubuntu-latest
    steps:
      - name: Install eza via apt repo
        run: |
          wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo tee /etc/apt/trusted.gpg.d/gierens.asc && \
          echo "deb http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list && \
          sudo apt update && \
          sudo apt install -y eza
      - name: Run eza
        run: eza
      - name: Open man page
        run: man eza | cat
